# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2023 Dell Inc, or its subsidiaries.
# Copyright (C) 2022 Marvell International Ltd.
---
version: "3.7"

services:

  opi-marvell-server:
    build:
      context: .
    ports:
      - "50051:50051"
    networks:
      - opi
    command: /opi-marvell-bridge -port=50051 -spdk_addr /var/tmp/spdk.sock
    healthcheck:
      test: grpcurl -plaintext localhost:50051 list || exit 1

  opi-test:
    image: docker.io/namely/grpc-cli
    networks:
      - opi
    depends_on:
      opi-marvell-server:
        condition: service_healthy
    command: ls opi-marvell-server:50051 opi_api.storage.v1.FrontendNvmeService -l

  opi-client:
    image: docker.io/opiproject/godpu:main
    networks:
      - opi
    depends_on:
      opi-marvell-server:
        condition: service_healthy
    command: storagetest --addr=opi-marvell-server:50051

networks:
  opi:
