# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
# Copyright (C) 2022 Marvell International Ltd.
---
version: "3.7"

services:

  opi-marvell-server:
    build:
      context: .
    ports:
      - "50051:50051"
    networks:
      - opi
    # command: /opi-marvell-bridge -port=50051
    command: go run main.go -port=50051

  opi-test:
    image: namely/grpc-cli
    networks:
      - opi
    depends_on:
      - opi-marvell-server
    command: ls opi-marvell-server:50051 opi_api.storage.v1.FrontendNvmeService -l

  opi-client:
    image: "ghcr.io/opiproject/opi-storage-client:main"
    networks:
      - opi
    depends_on:
      - opi-marvell-server
    command: /opi-storage-client -addr=opi-marvell-server:50051

networks:
  opi:
